mysqlbase:
  host: 127.0.0.1
  port: 3306
  sid: order
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysqlbase.host}:${mysqlbase.port}/${mysqlbase.sid}?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true
    username: root
    password: wyh900811@sina.com
mybatis-plus:
  type-aliases-package: com.csj.mapper
  mapper-locations: classpath:mapper/*Mapper.xml
